### ISSUE TITLE
About subsets evaluation

### ISSUE THREAD

**Issue by Violettttee** [TIGER-AI-Lab/MEGA-Bench#4]
Hi again again~
I wonder if i want the final score just as what the [leadboard](https://huggingface.co/spaces/TIGER-Lab/MEGA-Bench) shows, should i calculate the overall score by myself with the score for core and open sets?
Since i see in the arguments i must define "dataset_subset_name", i think does that mean the overall score is not automatically calculate by evaluation_processor?

**Comment by woodfrog** [comment]
Hi~ The evaluation processor will evaluate all results in the output file (by default, the output filename is `all_query_responses.json`). 

If you run the core set first and then run the open set using the same model output file, the final score output file will automatically contain the overall score. But if you run them separately and keep the results in different locations, the evaluation processor won't handle it, and you will need to calculate the weighted average yourself.

I will upload some example output files for reference.

**Comment by Violettttee** [comment]
@woodfrog I have tried the two sets and got the point!
Thanks a lot ~

**Comment by woodfrog** [comment]
Hi @Violettttee, just in case you need some reference, I uploaded example results with Qwen2-VL-7B [here](https://github.com/TIGER-AI-Lab/MEGA-Bench/tree/main/megabench/results/Qwen2_VL_7B). 

The numbers in those files are slightly different from the numbers in our paper/leaderboard because the data was changed a bit when we uploaded things to HF (e.g., a few duplicate samples were removed, and prompts were slightly adjusted), but it won't affect the overall comparison trend.

**Comment by Violettttee** [comment]
Hi~ @woodfrog , here seems to be a final question, since i see this code in the main.py
``` python
subset_dataset, all_dataset = prepare_megabench_data(args.dataset_name, args.dataset_subset_name)
```
which seems to assign a definite subset name to get all_dataset for "hf_data", does this mean i need to first run core and secondly open to get the final score?Can i put the core and open response altogether in the all_query_responses.json, and do evaluate as above two times?

**Comment by woodfrog** [comment]
Hi @Violettttee, thanks for your question. 

The `dataset_subset_name` only affects which subset the task processor runs and does not affect the evaluation. The evaluation processor will always evaluate all tasks in the given `responses.json` file. Therefore, passing `all_dataset` to the evaluation processor is to make sure it can access the metadata for all tasks so that the evaluation works for any `responses.json` file. Otherwise, suppose the responses file contains the results of all tasks (when we run two subsets and save the results into the same file), but only part of the task metadata is provided to the evaluation processor, the evaluation will have trouble.
